### ISSUE TITLE
Not working on HA  2021.3.4

### ISSUE THREAD

**Issue by tzungtzu** [nqkdev/home-assistant-vacuum-styj02ym#44]
hello, my homeassistant works on NAS(Docker) get this error info

`2021-06-22 15:30:13 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_miio: Unable to import component: cannot import name 'GatewayException' from 'miio.gateway' (/usr/local/lib/python3.8/site-packages/miio/gateway/__init__.py)
2021-06-22 15:30:27 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'GatewayException' from 'miio.gateway' (/usr/local/lib/python3.8/site-packages/miio/gateway/__init__.py)
2021-06-22 15:30:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved`

**Comment by Code-nomad** [comment]
change the miio version to 0.5.6 in your manifest.json file and this should resolve it. tested and confirmed working on my end.

{
    "domain": "miio2",
    "name": "Xiaomi miio vacuum STYJ02YM",
    "version": "1.0.0",
    "documentation": "",
    "requirements": [
        "construct==2.10.56",
        "python-miio==0.5.6"
    ],
    "dependencies": [],
    "codeowners": []
}

**Comment by dogmatic69** [comment]
Can you close this issue as it is resolved
