### ISSUE TITLE
Not working on a fresh install on HA 2021.1.4

### ISSUE THREAD

**Issue by wberrazeg** [nqkdev/home-assistant-vacuum-styj02ym#28]
HA 2021.1.4 on a NAS (Docker), getting this error message
```
Logger: frontend.js.latest.202012291
Source: components/system_log/__init__.py:193 
First occurred: 1:00:41 PM (1 occurrences) 
Last logged: 1:00:41 PM

:0:0 Script error.
```

**Comment by benimotive** [comment]
Same on 2021.1.5. 
Not reacting to commands

**Comment by dolohow** [comment]
Can't reproduce it

**Comment by chris24walsh** [comment]
It's also not working for me, I'm on version 2021.3.4. I get errors like this in the logs:

```
2021-04-13 08:11:41 WARNING (SyncWorker_0) [custom_components.miio2.vacuum] Got exception while fetching the state: Unable to discover the device 192.168.68.157
2021-04-13 08:11:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'GatewayException' from 'miio.gateway' (/usr/local/lib/python3.8/site-packages/miio/gateway/__init__.py)
```

My configuration.yaml looks like this:

```
vacuum:
  - platform: miio2
    host: 192.168.68.157
    token: <token>
    name: VacuumMop
```

In the UI, the vacuum entity card shows as unavailable.

I've tried updating python-miio to 0.5.5.2 (latest) and even altering the vacuum.py code to use the ViomiVacuum module  from miio, I get the same errors.
I tried using @dolohow repo instead of @nqkdev but still no joy :/ That's actually what gives me the Gateway error shown above.

**Comment by chris24walsh** [comment]
By the way, I have issues using miiocli to get the state too - it always times out. Looking at the debug output, seems the seq id's used are always the same, and seem to be dropped by the device. When I try to use the viomivacuum subcommand instead, it works - although its slow, has to retry a lot to find a new unused seq id.

**Comment by JoaquinBeceiro** [comment]
Solved on https://github.com/nqkdev/home-assistant-vacuum-styj02ym/pull/36 .
New HA demands version on manifest
